### ISSUE TITLE
Lab2で必要なguestbookアプリがLab1の手順の最後に削除されている

### ISSUE THREAD

**Issue by kissyy** [capsmalt/sandbox#1]
Lab1では最後にguestbookアプリをすべて削除していますが、
その次のLab2ですぐにまた同じguestbookアプリをデプロイしています。
なんか特別な意図があるのでしょうか？

**Comment by capsmalt** [comment]
全てのLabにおいて独立性を担保するためです。なので，必要なものはLabの最初に準備するスタイルで良いと思っています。
